stages:
- docs
- testing
- coverage

image: centos:7

.install_template: &install_python
  before_script:
    - yum -y install https://centos7.iuscommunity.org/ius-release.rpm
    - yum -y install python36u
    - yum -y install pypy
    - yum -y install docker
    - python3.6 -m ensurepip
    - python3.6 -m pip install --user tox

.testing_template: &testing_definition
  stage: testing
  tags:
    - docker-privileged
  services:
    - docker:dind
  variables:
    # When using dind service we need to instruct docker, to talk with the
    # daemon started inside of the service. The daemon is available with
    # a network connection instead of the default /var/run/docker.sock socket.
    #
    # The 'docker' hostname is the alias of the service container as described at
    # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
    #
    # Note that if you're using Kubernetes executor, the variable should be set to
    # tcp://localhost:2375 because of how Kubernetes executor connects services
    # to the job container
    DOCKER_HOST: tcp://docker:2375/
    # When using dind, it's wise to use the overlayfs driver for
    # improved performance.
    DOCKER_DRIVER: overlay2
  artifacts:
    paths:
      - '.coverage.${envname}'
  script:
    - python3.6 -m tox -e ${envname}

build_docs:
  stage: docs
  before_script:
  script:
    - curl -X POST https://readthedocs.org/api/v2/webhook/gitlab-runner-api/50613/
      -d "branches=${CI_COMMIT_REF_NAME}"
      -d "token=${READTHEDOCS_TOKEN}"

test:py27:
  <<: *install_python
  <<: *testing_definition
  variables:
    envname: py27
    PYTHON_EXECUTABLE: python2.7

test:py36:
  <<: *install_python
  <<: *testing_definition
  variables:
    envname: py36
    PYTHON_EXECUTABLE: python3.6

test:pypy:
  <<: *install_python
  <<: *testing_definition
  variables:
    envname: pypy
    PYTHON_EXECUTABLE: pypy

coverage:
  <<: *install_python
  stage: coverage
  dependencies:
    - test:py27
    - test:py36
    - test:pypy
  script:
    - python3.6 -m tox -e cov-report
