name: gitlab-runner-api-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - pip
  - colorlog
  - pytest
  - pytest-cov
  - requests
  - requests-toolbelt
  - responses
  - setuptools_scm
  - six
